server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPOSITORY:classpath:/config-repository}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    config:
      enabled: false
