server:
  port: 8083

spring:
  liquibase:
    change-log: classpath:db/changelog/dialog-service.yaml
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/dialog}
    username: ${DB_USER:dialog}
    password: ${DB_PASSWORD:dialog}
