server:
  port: 8082

spring:
  liquibase:
    change-log: classpath:db/changelog/persona-service.yaml
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/persona}
    username: ${DB_USER:persona}
    password: ${DB_PASSWORD:persona}
